export let cities = [

    {
        name: "Los Angeles",
        state: "California",
        isCapital: false,
        alt: "Los Angeles",
        image: "https://images.unsplash.com/photo-1523413651479-597eb2da0ad6",
        isOnTheCoast: true,
        isRomantic: false,
        isModern: true,
        size: "large",
        isEnglishMainLanguage: true,
        temperature: "mild"
      },
      {
        name: "Chicago",
        state: "Illinois",
        isCapital: false,
        alt: "Chicago",
        image: "https://images.unsplash.com/photo-1560177115-82dbf6b316fc",
        isOnTheCoast: false,
        isRomantic: false,
        isModern: true,
        size: "large",
        isEnglishMainLanguage: true,
        temperature: "cold"
      },
      {
        name: "Houston",
        state: "Texas",
        isCapital: false,
        alt: "Houston",
        image: "https://images.unsplash.com/photo-1534361960059-f4157c876b50",
        isOnTheCoast: true,
        isRomantic: false,
        isModern: true,
        size: "large",
        isEnglishMainLanguage: true,
        temperature: "hot"
      },
      {
        name: "Philadelphia",
        state: "Pennsylvania",
        isCapital: false,
        alt: "Philadelphia",
        image: "https://images.unsplash.com/photo-1493143847598-47a08f884dce",
        isOnTheCoast: true,
        isRomantic: false,
        isModern: true,
        size: "medium",
        isEnglishMainLanguage: true,
        temperature: "mild"
      },

      {
          name: "Tokyo",
          country: "Japan",
          isCapital: true,
          alt: "Tokyo",
          image: "https://images.unsplash.com/photo-1538434924081-aee1f7dd1c45",
          isOnTheCoast: true,
          isRomantic: false,
          isModern: true,
          size: "large",
          isEnglishMainLanguage: false,
          temperature: "mild"
        },
        {
          name: "Shanghai",
          country: "China",
          isCapital: false,
          alt: "Shanghai",
          image: "https://images.unsplash.com/photo-1559105054-8db96cbeb3d9",
          isOnTheCoast: true,
          isRomantic: false,
          isModern: true,
          size: "large",
          isEnglishMainLanguage: false,
          temperature: "mild"
        },
        {
          name: "Beijing",
          country: "China",
          isCapital: true,
          alt: "Beijing",
          image: "https://images.unsplash.com/photo-1559928892-0d18a7bfbfae",
          isOnTheCoast: false,
          isRomantic: false,
          isModern: true,
          size: "large",
          isEnglishMainLanguage: false,
          temperature: "cold"
        },
        {
          name: "Seoul",
          country: "South Korea",
          isCapital: true,
          alt: "Seoul",
          image: "https://images.unsplash.com/photo-1574232577843-1ef90c3c3cd3",
          isOnTheCoast: true,
          isRomantic: false,
          isModern: true,
          size: "large",
          isEnglishMainLanguage: false,
          temperature: "mild"
        },
        {
          name: "Hong Kong",
          country: "China",
          isCapital: false,
          alt: "Hong Kong",
          image: "https://images.unsplash.com/photo-1564070395227-d68b8a1fba96",
          isOnTheCoast: true,
          isRomantic: false,
          isModern: true,
          size: "medium",
          isEnglishMainLanguage: false,
          temperature: "mild"
        },
        {
          name: "Bangkok",
          country: "Thailand",
          isCapital: true,
          alt: "Bangkok",
          image: "https://images.unsplash.com/photo-1541635250-982f6a58e1e0",
          isOnTheCoast: false,
          isRomantic: false,
          isModern: true,
          size: "large",
          isEnglishMainLanguage: false,
          temperature: "hot"
        },
        {
          name: "Mumbai",
          country: "India",
          isCapital: false,
          alt: "Mumbai",
          image: "https://images.unsplash.com/photo-1602513982478-27a2c3c3b0c9",
          isOnTheCoast: true,
          isRomantic: false,
          isModern: true,
          size: "large",
          isEnglishMainLanguage: false,
          temperature: "hot"
        },

        {
            name: "New York",
            state: "New York",
            isCapital: false,
            alt: "New York",
            image: "https://images.unsplash.com/photo-1533075373013-15a43a56a8f0",
            isOnTheCoast: true,
            isRomantic: true,
            isModern: true,
            size: "large",
            isEnglishMainLanguage: true,
            temperature: "mild"
          },
        
          {
            name: "Sao Paulo",
            country: "Brazil",
            isCapital: false,
            alt: "Sao Paulo",
            image: "https://images.unsplash.com/photo-1535398094883-a56a3b6a012c",
            isOnTheCoast: false,
            isRomantic: false,
            isModern: true,
            size: "large",
            isEnglishMainLanguage: false,
            temperature: "hot"
          },
          {
            name: "Buenos Aires",
            country: "Argentina",
            isCapital: false,
            alt: "Buenos Aires",
            image: "https://images.unsplash.com/photo-1615494417297-c83f86ed25a7",
            isOnTheCoast: true,
            isRomantic: false,
            isModern: false,
            size: "large",
            isEnglishMainLanguage: false,
            temperature: "mild"
          },
          {
            name: "Rio de Janeiro",
            country: "Brazil",
            isCapital: false,
            alt: "Rio de Janeiro",
            image: "https://images.unsplash.com/photo-1571369307869-b55d8a7a0f60",
            isOnTheCoast: true,
            isRomantic: true,
            isModern: true,
            size: "medium",
            isEnglishMainLanguage: false,
            temperature: "hot"
          },
          {
            name: "Lima",
            country: "Peru",
            isCapital: true,
            alt: "Lima",
            image: "https://images.unsplash.com/photo-1528642474491-44a342a45c35",
            isOnTheCoast: true,
            isRomantic: false,
            isModern: false,
            size: "large",
            isEnglishMainLanguage: false,
            temperature: "mild"
          },
          {
            name: "Santiago",
            country: "Chile",
            isCapital: true,
            alt: "Santiago",
            image: "https://images.unsplash.com/photo-1530786620401-979c4f779a79",
            isOnTheCoast: false,
            isRomantic: false,
            isModern: false,
            size: "large",
            isEnglishMainLanguage: false,
            temperature: "mild"
          },
          {
            name: "Bogota",
            country: "Colombia",
            isCapital: true,
            alt: "Bogota",
            image: "https://images.unsplash.com/photo-1511556820780-a2eb1e148f8a",
            isOnTheCoast: false,
            isRomantic: false,
            isModern: false,
            size: "large",
            isEnglishMainLanguage: false,
            temperature: "hot"
          },
          {
            name: "Montevideo",
            country: "Uruguay",
            isCapital: true,
            alt: "Montevideo",
            image: "https://images.unsplash.com/photo-1548188464-58e27d49f6ef",
            isOnTheCoast: true,
            isRomantic: false,
            isModern: true,
            size: "medium",
            isEnglishMainLanguage: false,
            temperature: "mild"
          },
    
          {
            name: "Dubai",
            country: "United Arab Emirates",
            isCapital: false,
            alt: "Dubai",
            image: "https://images.unsplash.com/photo-1552083375-5f5a5e47e5b6",
            isOnTheCoast: true,
            isRomantic: false,
            isModern: true,
            size: "large",
            isEnglishMainLanguage: true,
            temperature: "hot"
          },
          {
            name: "Moscow",
            country: "Russia",
            isCapital: true,
            alt: "Moscow",
            image: "https://images.unsplash.com/photo-1513135060220-764a0c7249c5",
            isOnTheCoast: false,
            isRomantic: false,
            isModern: true,
            size: "large",
            isEnglishMainLanguage: false,
            temperature: "cold"
          },
          {
            name: "Saint Petersburg",
            country: "Russia",
            isCapital: false,
            alt: "Saint Petersburg",
            image: "https://images.unsplash.com/photo-1546523582-9be6f61cfe1d",
            isOnTheCoast: true,
            isRomantic: true,
            isModern: false,
            size: "large",
            isEnglishMainLanguage: false,
            temperature: "cold"
          },
          {
            name: "Helsinki",
            country: "Finland",
            isCapital: true,
            alt: "Helsinki",
            image: "https://images.unsplash.com/photo-1534043460179-9c5c5d6dc5c2",
            isOnTheCoast: true,
            isRomantic: false,
            isModern: true,
            size: "medium",
            isEnglishMainLanguage: false,
            temperature: "cold"
          },
          {
            name: "Montreal",
            country: "Canada",
            isCapital: false,
            alt: "Montreal",
            image: "https://images.unsplash.com/photo-1531969782429-8a22e3cb3c12",
            isOnTheCoast: false,
            isRomantic: false,
            isModern: true,
            size: "large",
            isEnglishMainLanguage: true,
            temperature: "cold"
          },
          {
            name: "Cape Town",
            country: "South Africa",
            isCapital: false,
            alt: "Cape Town",
            image: "https://images.unsplash.com/photo-1553688738-53040b1615a5",
            isOnTheCoast: true,
            isRomantic: true,
            isModern: true,
            size: "large",
            isEnglishMainLanguage: true,
            temperature: "mild"
          },
          {
            name: "Mexico City",
            country: "Mexico",
            isCapital: true,
            alt: "Mexico City",
            image: "https://images.unsplash.com/photo-1544594256-5a810fda9665",
            isOnTheCoast: false,
            isRomantic: false,
            isModern: true,
            size: "large",
            isEnglishMainLanguage: false,
            temperature: "mild"
          },
        
          {
            name: "Paris",
            country: "France",
            isCapital: false,
            alt: "Paris",
            image: "https://images.unsplash.com/photo-1543361194-0b0c8b416c50",
            isOnTheCoast: false,
            isRomantic: true,
            isModern: true,
            size: "large",
            isEnglishMainLanguage: false,
            temperature: "mild"
          },
          {
            name: "London",
            country: "United Kingdom",
            isCapital: true,
            alt: "London",
            image: "https://images.unsplash.com/photo-1523987359423-3ec3fa3dc34f",
            isOnTheCoast: false,
            isRomantic: false,
            isModern: true,
            size: "large",
            isEnglishMainLanguage: true,
            temperature: "mild"
          },
          {
            name: "Berlin",
            country: "Germany",
            isCapital: true,
            alt: "Berlin",
            image: "https://images.unsplash.com/photo-1534740772-0e31bf6c5263",
            isOnTheCoast: false,
            isRomantic: false,
            isModern: true,
            size: "large",
            isEnglishMainLanguage: false,
            temperature: "mild"
          },
          {
            name: "Madrid",
            country: "Spain",
            isCapital: true,
            alt: "Madrid",
            image: "https://images.unsplash.com/photo-1516233035025-5a810fda9665",
            isOnTheCoast: false,
            isRomantic: false,
            isModern: true,
            size: "large",
            isEnglishMainLanguage: false,
            temperature: "mild"
          },
          {
            name: "Barcelona",
            country: "Spain",
            isCapital: false,
            alt: "Barcelona",
            image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97",
            isOnTheCoast: true,
            isRomantic: true,
            isModern: true,
            size: "large",
            isEnglishMainLanguage: false,
            temperature: "mild"
          },
          {
            name: "Rome",
            country: "Italy",
            isCapital: true,
            alt: "Rome",
            image: "https://images.unsplash.com/photo-1555317027-f62a8f6e9c91",
            isOnTheCoast: false,
            isRomantic: true,
            isModern: false,
            size: "large",
            isEnglishMainLanguage: false,
            temperature: "mild"
          },
          {
            name: "Milan",
            country: "Italy",
            isCapital: false,
            alt: "Milan",
            image: "https://images.unsplash.com/photo-1534466853289-e3ab04d986ba",
            isOnTheCoast: false,
            isRomantic: false,
            isModern: true,
            size: "large",
            isEnglishMainLanguage: false,
            temperature: "mild"
          },
          
          {
            name: "Amsterdam",
            country: "Netherlands",
            isCapital: false,
            alt: "Amsterdam",
            image: "https://cdn.pixabay.com/photo/2018/08/22/11/20/amsterdam-3625263_1280.jpg",
            isOnTheCoast: true,
            isRomantic: true,
            isModern: false,
            size: "medium",
            isEnglishMainLanguage: false,
            temperature: "cold"
          },
          {
            name: "Vienna",
            country: "Austria",
            isCapital: true,
            alt: "Vienna",
            image: "https://cdn.pixabay.com/photo/2018/03/06/14/44/vienna-3200028_1280.jpg",
            isOnTheCoast: false,
            isRomantic: true,
            isModern: false,
            size: "large",
            isEnglishMainLanguage: false,
            temperature: "cold"
          },
          {
            name: "Stockholm",
            country: "Sweden",
            isCapital: true,
            alt: "Stockholm",
            image: "https://cdn.pixabay.com/photo/2018/09/03/09/28/stockholm-3651544_1280.jpg",
            isOnTheCoast: true,
            isRomantic: true,
            isModern: true,
            size: "medium",
            isEnglishMainLanguage: false,
            temperature: "cold"
          },
          {
            name: "Brussels",
            country: "Belgium",
            isCapital: "yes",
            alt: "Brussels",
            image: "https://cdn.pixabay.com/photo/2014/03/14/15/15/brussels-287423_1280.jpg",
            isOnTheCoast: "no",
            isRomantic: "yes",
            isModern: "yes",
            size: "small",
            isEnglishMainLanguage: "no",
            temperature: "mild"
          },
          {
            name: "Zurich",
            country: "Switzerland",
            isCapital: "no",
            alt: "Zurich",
            image: "https://cdn.pixabay.com/photo/2017/09/18/17/46/zurich-2762580_1280.jpg",
            isOnTheCoast: "no",
            isRomantic: "yes",
            isModern: "yes",
            size: "small",
            isEnglishMainLanguage: "yes",
            temperature: "mild"
          },
          {
            name: "Athens",
            country: "Greece",
            isCapital: "yes",
            alt: "Athens",
            image: "https://cdn.pixabay.com/photo/2019/09/02/16/25/athens-4446253_1280.jpg",
            isOnTheCoast: "yes",
            isRomantic: "yes",
            isModern: "no",
            size: "large",
            isEnglishMainLanguage: "no",
            temperature: "hot"
          },

          {
            name: "Cairo",
            country: "Egypt",
            isCapital: true,
            alt: "Cairo",
            image: "https://upload.wikimedia.org/wikipedia/commons/0/0b/Cairo_Egypt.jpg",
            isOnTheCoast: false,
            isRomantic: false,
            isModern: true,
            size: "large",
            isEnglishMainLanguage: false,
            temperature: "hot"
          },
          {
            name: "Johannesburg",
            country: "South Africa",
            isCapital: false,
            alt: "Johannesburg",
            image: "https://upload.wikimedia.org/wikipedia/commons/f/f2/Johannesburg_Skyline.jpg",
            isOnTheCoast: false,
            isRomantic: false,
            isModern: true,
            size: "large",
            isEnglishMainLanguage: true,
            temperature: "mild"
          },
          {
            name: "Lagos",
            country: "Nigeria",
            isCapital: false,
            alt: "Lagos",
            image: "https://upload.wikimedia.org/wikipedia/commons/c/c4/Lagos_Island_1.jpg",
            isOnTheCoast: true,
            isRomantic: false,
            isModern: false,
            size: "large",
            isEnglishMainLanguage: true,
            temperature: "hot"
          },
          {
            name: "Addis Ababa",
            country: "Ethiopia",
            isCapital: true,
            alt: "Addis Ababa",
            image: "https://upload.wikimedia.org/wikipedia/commons/f/f9/Addis_Ababa_Skyline.jpg",
            isOnTheCoast: false,
            isRomantic: false,
            isModern: false,
            size: "medium",
            isEnglishMainLanguage: false,
            temperature: "hot"
          },
          {
            name: "Casablanca",
            country: "Morocco",
            isCapital: false,
            alt: "Casablancaʼ",
            image: "https://upload.wikimedia.org/wikipedia/commons/5/5e/Casablanca_Mohammed_V_Airport_11.jpg",
            isOnTheCoast: true,
            isRomantic: true,
            isModern: true,
            size: "large",
            isEnglishMainLanguage: false,
            temperature: "hot"
          },
          {
            name: "Nairobi",
            country: "Kenya",
            isCapital: true,
            alt: "Nairobi",
            image: "https://upload.wikimedia.org/wikipedia/commons/f/f1/Nairobi_skyline.jpg",
            isOnTheCoast: false,
            isRomantic: false,
            isModern: false,
            size: "large",
            isEnglishMainLanguage: true,
            temperature: "hot"
          },
          {
            name: "Dakar",
            country: "Senegal",
            isCapital: false,
            alt: "Dakar",
            image: "https://upload.wikimedia.org/wikipedia/commons/9/9e/Route_de_la_Corniche%2C_Dakar.jpg",
            isOnTheCoast: true,
            isRomantic: false,
            isModern: false,
            size: "large",
            isEnglishMainLanguage: false,
            temperature: "hot"
          },

          { 
            name: "Naples",
            country: "Italy",
            isCapital: false,
            alt: "Napoli",
            image: "https://www.visitnaples.eu/sites/visitnaples.eu/files/styles/large/public/2019-05/naples-4126768_1920.jpg?itok=iFw6xaw2",
            isOnTheCoast: true,
            isRomantic: true,
            isModern: false,
            size: "medium",
            isEnglishMainLanguage: false,
            temperature: "mild"
          },
          { 
            name: "Marseille",
            country: "France",
            isCapital: false,
            alt: "Marsiglia",
            image: "https://cdn.getyourguide.com/img/tour_img-2360767-146.jpg",
            isOnTheCoast: true,
            isRomantic: true,
            isModern: false,
            size: "small",
            isEnglishMainLanguage: false,
            temperature: "mild"
          },
          { 
            name: "Valencia",
            country: "Spain",
            isCapital: false,
            alt: "València",
            image: "https://www.visitvalencia.com/sites/default/files/styles/slider_home/public/2020-03/valenciaturisticacovid19.jpg?itok=i0BjKw3r",
            isOnTheCoast: true,
            isRomantic: false,
            isModern: true,
            size: "large",
            isEnglishMainLanguage: false,
            temperature: "mild"
          },
          { 
            name: "Singapore",
            country: "Singapore",
            isCapital: true,
            alt: "Singapura",
            image: "https://www.visitsingapore.com/etc/designs/singapore/v3-campaigns/singapore-insiders-guide/desktop/hero_image.jpg",
            isOnTheCoast: true,
            isRomantic: false,
            isModern: true,
            size: "medium",
            isEnglishMainLanguage: true,
            temperature: "hot"
          },
          { 
            name: "Melbourne",
            country: "Australia",
            isCapital: false,
            alt: "Melburne",
            image: "https://www.visitmelbourne.com/-/media/images/melbourne/regions/melbourne-city/_8140172_2048x1024_supplied.jpeg?ts=20210401092315&crop=0,126,2048,948&resize=2048,948",
            isOnTheCoast: true,
            isRomantic: false,
            isModern: true,
            size: "large",
            isEnglishMainLanguage: true,
            temperature: "mild"
          },
          { 
            name: "Johannesburg",
            country: "South Africa",
            isCapital: false,
            alt: "Jozi",
            image: "https://www.southafrica.net/wp-content/uploads/2020/09/johannesburg_city_of_gold_1.jpg",
            isOnTheCoast: false,
            isRomantic: false,
            isModern: true,
            size: "large",
            isEnglishMainLanguage: true,
            temperature: "mild"
          }]
      
        
      
        
        
        

        
        
        
        
        
        
        
      
      